name: stream_analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - scipy=1.13
  - h5py=3.12
  - astropy=6.1
  - matplotlib=3.9
  - numpy=1.22
  - jupyterlab
  - ipykernel
  - pandas
  - pip 
  - pip:
    - /home-filer/sferrone/gcs/
