name: stream_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9,<3.12
  - numpy>=1.20
  - setuptools>=65.5
  - astropy>=6.0
  - jupyterlab>=4.2  
  - pyyaml>=6.0
  - h5py>=3.11
  - matplotlib>=3.7
  - pytest
  - gcc
  - gfortran
  - meson 
  - ipykernel
  - scipy 
  - pip 
  - pandas 
  - snakeviz
  - pip:
    - /obs/sferrone/gcs/
    - /obs/sferrone/stream_analysis/