name: stream_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.20
  - numpy==1.22
  - gcc==11.2.0
  - gfortran
  - setuptools=68.2
  - astropy==5.0
  - matplotlib==3.5
  - jupyterlab==4.2  
  - pyyaml==6.0.1
  - h5py==3.11.0
  - ipykernel
  - scipy 
  - pip 
  - pandas 
  - pip:
    - /obs/sferrone/gcs/
    - /obs/sferrone/stream_analysis/
    - /obs/sferrone/tstrippy/